on: [push, pull_request]
name: Quality assurance
jobs:
  phpstan:
    name: PHPStan

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: PHPStan
        uses: "docker://oskarstark/phpstan-ga"
        env:
          REQUIRE_DEV: 'true'
          CHECK_PLATFORM_REQUIREMENTS: false
        with:
          args: analyse

  psalm:
    name: Psalm

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          tools: composer:v2

      - name: Set Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-7.4-composer-highest-normal
          restore-keys: ${{ runner.os }}-7.4-composer-

      - name: Install Composer dependencies (highest)
        run: composer update --prefer-dist --no-progress --no-interaction --prefer-stable

      - name: Psalm
        run: vendor/bin/psalm --show-info=false --stats --output-format=github --threads=$(nproc) --shepherd
